export const skills = {
  "Frameworks & Libraries": [
    "React.js",
    "Next.js",
    "Redux",
    "Redux-Saga",
    "TanStack Query",
    "Jotai",
    "Angular",
    "AngularJS",
    "jQuery",
    "Ionic",
    "Node.js",
    "MUI",
  ],
  "Languages & Markup": [
    "TypeScript",
    "JavaScript",
    "HTML",
    "CSS",
    "SASS/SCSS",
  ],
  "CSS-in-JS": ["Styled Components", "MUI Styled"],
  "Tools & Platforms": [
    "Webpack",
    "Vite",
    "Vitest",
    "Cypress",
    "Playwright",
    "Git",
    "GitHub Actions",
    "CI/CD",
    "REST APIs",
    "Payload CMS",
    "Figma",
    "Adobe Creative Suite",
  ],
  Practices: [
    "Agile",
    "Scrum",
    "Code Review",
    "Component Architecture",
    "Performance Optimization",
    "Responsive Design",
    "Cross-browser Compatibility",
    "Mentoring",
  ],
};
